language: java
branches:
  only:
    - develop
script: "cd languages/Natlab; ant test"
notifications:
  email:
    recipients:
      - mclab@sable.mcgill.ca
    on_success: change
    on_failure: always
